version: "3"

services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules # to avoid copy this folder
    environment:
      - NODE_ENV=development
    command: mpn run dev
